function renderBoard(){
 $('#boardGameTitle').textContent=config.gameName;const board=$('#board');const currentMission=missionAt(Math.min(run.missionIndex,5));
 const currentProgress=Math.min(6,run.missionIndex+1);
 const cpClass=p=>{const reached=Math.max(...run.teams.map(t=>t.progress));return `${reached>=p?'done ':''}${!run.gameComplete&&currentProgress===p?'active':''}`};
 const slots=()=>Array.from({length:6},()=>'<div class="mb-slot"></div>').join('');
 const checkpoint=(round,cp,progress)=>`<div class="mb-checkpoint cp${cp} ${cpClass(progress)}"><div class="mb-cp-head"><span class="flag">⚑</span><span>CP ${cp}</span></div><div class="mb-slots">${slots()}</div></div>`;
 const legend=run.teams.map((t,i)=>`<div class="mb-legend-item" style="background:${TEAM_COLORS[i]}18"><span class="mb-legend-dot" style="background:${TEAM_COLORS[i]}"></span><span>K${i+1}</span></div>`).join('');
 board.innerHTML=`
  <div class="mb-title"><div class="mb-title-main">TODAY MISSION</div><div class="mb-title-sub">${esc(config.gameName||'SOC MISSION BOARD')}</div></div>
  <div class="mb-round r1"><div class="mb-track"></div><div class="mb-round-label">ROUND 1</div>${checkpoint(1,1,1)}${checkpoint(1,2,2)}</div>
  <div class="mb-round r2"><div class="mb-track"></div><div class="mb-round-label">ROUND 2</div>${checkpoint(2,1,3)}${checkpoint(2,2,4)}</div>
  <div class="mb-round r3"><div class="mb-track"></div><div class="mb-round-label">ROUND 3</div>${checkpoint(3,1,5)}${checkpoint(3,2,6)}</div>
  <div class="mb-start"><div class="inner"><span class="flag">⚑</span>START</div></div>
  <div class="mb-finish"><div class="inner"><span class="flag">🏆</span>FINISH</div></div>
  <div class="mb-team-legend">${legend}</div>`;
 run.teams.forEach((t,i)=>{const d=document.createElement('div');d.className=`pawn p${i+1}`;d.id=`pawn${i}`;const displayProgress=moveAnimation?moveAnimation.from[i]:t.progress;const p=pawnPosition(displayProgress,i);d.style.left=p.x+'%';d.style.top=p.y+'%';d.innerHTML=`<span>${i+1}</span>`;board.appendChild(d)});
 $('#progressPanel').innerHTML=run.teams.map((t,i)=>`<div class="team-progress"><div class="dot" style="background:${TEAM_COLORS[i]}">${i+1}</div><div><b>${esc(t.name)}</b><small>${progressLabel(t.progress)}</small></div><div class="score-pill">${t.score+t.flash}</div></div>`).join('');
 const next=$('#boardNextBtn'); if(run.gameComplete){next.textContent='🏆 Lihat Hasil Akhir';next.onclick=()=>go('scoreboard')} else if(!run.started){next.textContent='Mulai Misi →';next.onclick=()=>beginMission()} else {const mi=run.missionIndex;next.textContent=mi===0?'Mulai Misi →':(mi%2===0?'Next Round →':'Lanjutkan Misi →');next.onclick=()=>beginMission()}
}

function beginMission(){if(run.gameComplete)return go('scoreboard');run.started=true;run.drafts=Array(6).fill(null);run.locked=Array(6).fill(false);run.revealed=false;run.pendingMoves=Array(6).fill(false);saveRun();renderMission();go('mission')}
$('#startGameBtn').onclick=()=>{if(!run.started&&run.missionIndex===0)go('board');else go('board')};
$('#resetRunBtn').onclick=()=>{run=newRun();saveRun();renderBoard();toast('Run permainan direset. Konfigurasi dan data tes tetap aman.')};
function renderMission(){const {round,mission,r,m}=missionAt();$('#missionRoundTag').textContent=`ROUND ${r+1} • MISSION ${m+1}`;$('#missionRoundName').textContent=round.name;$('#missionName').textContent=mission.name;$('#difficultyBadge').textContent=round.difficulty;$('#questionText').textContent=mission.question;
 const opts=$('#questionOptions'); if(mission.type==='structured'){opts.innerHTML=mission.options.map((x,i)=>`<div class="option-preview"><b>${i+1}. ${esc(x)}</b><div class="muted mini">Pilih A / B / C / D</div></div>`).join('')}else if(mission.type==='truefalse'){opts.innerHTML='<div class="option-preview"><b>BENAR</b></div><div class="option-preview"><b>SALAH</b></div>'}else opts.innerHTML=mission.options.map(x=>`<div class="option-preview">${esc(x)}</div>`).join('');
 $('#teamAnswers').innerHTML=run.teams.map((t,i)=>answerCard(i,mission)).join('');bindAnswerEvents(mission);updateLockCounter()}
function answerCard(i,mission){let control='';if(mission.type==='structured'){control=`<div class="structured">${mission.options.map((label,j)=>`<div class="structured-row"><span class="mini muted">${esc(label)}</span><select class="struct-select" data-team="${i}" data-part="${j}"><option value="">—</option><option>A</option><option>B</option><option>C</option><option>D</option></select></div>`).join('')}</div>`}else{const vals=mission.type==='truefalse'?['BENAR','SALAH']:['A','B','C','D'];control=`<div class="answer-select">${vals.map(v=>`<button type="button" data-team="${i}" data-val="${v}">${v}</button>`).join('')}</div>`}return `<div class="team-answer" id="teamAnswer${i}"><div class="team-answer-head"><b>${esc(run.teams[i].name)}</b><span class="status-badge">READY</span></div>${control}<button class="btn secondary lock-btn" data-team="${i}">🔒 LOCK ANSWER</button></div>`}
function bindAnswerEvents(mission){$$('.answer-select button').forEach(b=>b.onclick=()=>{const i=+b.dataset.team;if(run.locked[i])return;run.drafts[i]=b.dataset.val;$$(`.answer-select button[data-team="${i}"]`).forEach(x=>x.classList.toggle('selected',x===b))});$$('.lock-btn').forEach(b=>b.onclick=()=>lockAnswer(+b.dataset.team,mission))}
function lockAnswer(i,mission){if(run.locked[i])return;let val=run.drafts[i];if(mission.type==='structured'){const sels=$$(`.struct-select[data-team="${i}"]`);const arr=sels.map(s=>s.value);if(arr.some(v=>!v))return toast('Lengkapi 5 komponen jawaban kelompok ini.');val=arr.join('|');run.drafts[i]=val}else if(!val)return toast('Pilih jawaban terlebih dahulu.');run.locked[i]=true;saveRun();const card=$(`#teamAnswer${i}`);card.classList.add('locked');card.querySelector('.status-badge').textContent='🔒 ANSWER LOCKED';card.querySelectorAll('.answer-select,.structured').forEach(x=>x.style.display='none');card.querySelector('.lock-btn').style.display='none';updateLockCounter()}
function updateLockCounter(){const n=run.locked.filter(Boolean).length;$('#lockCounter').textContent=`${n} / 6 ANSWER LOCKED`;$('#revealBtn').disabled=n<6||run.revealed}
$('#revealBtn').onclick=()=>revealAnswers();
function norm(v){return String(v??'').trim().toUpperCase().replace(/\s+/g,'')}
function revealAnswers(){const {mission,r}=missionAt();if(run.locked.some(x=>!x))return;run.revealed=true;run.teams.forEach((t,i)=>{const ok=norm(run.drafts[i])===norm(mission.answer);t.lastCorrect=ok;t.answers.push({missionIndex:run.missionIndex,answer:run.drafts[i],correct:ok});run.pendingMoves[i]=ok;if(ok){t.score+=mission.score;t.roundScores[r]+=mission.score}});saveRun();renderResult();go('result')}
function renderResult(){const {mission}=missionAt();$('#correctAnswerDisplay').textContent=mission.answer.replaceAll('|',' • ');$('#answerExplanation').textContent=mission.explanation||'';$('#resultGrid').innerHTML=run.teams.map((t,i)=>`<div class="result-card ${t.lastCorrect?'ok':'no'}"><div class="team-answer-head"><b>${esc(t.name)}</b><span style="font-size:1.5rem">${t.lastCorrect?'✓':'✗'}</span></div><div style="font-weight:900;color:${t.lastCorrect?'var(--green)':'var(--red)'}">${t.lastCorrect?'CORRECT — PAWN WILL MOVE':'NOT YET — PAWN STAYS'}</div><div class="muted mini" style="margin-top:5px">${t.lastCorrect?`+${mission.score} poin`:'Review your answer and prepare for the next mission.'}</div></div>`).join('')}
$('#goBoardAfterResult').onclick=()=>applyMovesAndBoard();
function applyMovesAndBoard(){const moved=[];const from=run.teams.map(t=>t.progress);run.pendingMoves.forEach((ok,i)=>{if(ok){run.teams[i].progress=Math.min(6,run.teams[i].progress+1);moved.push(run.teams[i].name)}});const to=run.teams.map(t=>t.progress);moveAnimation={from,to};run.missionIndex++;
 const justFinishedRound=run.missionIndex%2===0;if(run.missionIndex>=6){run.gameComplete=true;run.missionIndex=5}saveRun();go('board');
 setTimeout(()=>{to.forEach((progress,i)=>{const pawn=$(`#pawn${i}`),p=pawnPosition(progress,i);if(pawn){pawn.style.left=p.x+'%';pawn.style.top=p.y+'%'}})},120);
 setTimeout(()=>{moveAnimation=null;if(moved.length){$('#celebrateTitle').textContent=run.gameComplete?'MISSION COMPLETE!':'✓ MISSION COMPLETE!';$('#celebrateText').textContent=`${moved.join(', ')} bergerak ke checkpoint berikutnya.`;$('#celebration').classList.add('show')}else if(justFinishedRound){toast('Round selesai. Tidak ada pion yang bergerak pada misi ini.')}},1450)}
$('#closeCelebrate').onclick=()=>$('#celebration').classList.remove('show');
function renderScoreboard(){const rows=run.teams.map((t,i)=>({i,t,total:t.score+(+t.flash||0)})).sort((a,b)=>b.total-a.total||b.t.progress-a.t.progress);$('#scoreBody').innerHTML=rows.map((x,rank)=>`<tr class="${rank===0?'winner':''}"><td class="rank">${rank===0?'🏆 ':''}${rank+1}</td><td><b>${esc(x.t.name)}</b></td><td>${x.t.roundScores[0]}</td><td>${x.t.roundScores[1]}</td><td>${x.t.roundScores[2]}</td><td>${x.t.flash||0}</td><td><b>${x.total}</b></td><td>${x.t.progress}/6</td></tr>`).join('');$('#flashInputs').innerHTML=run.teams.map((t,i)=>`<div class="field"><label class="label">${esc(t.name)}</label><input type="number" class="flash-score" data-i="${i}" min="0" max="10" value="${t.flash||0}"></div>`).join('')}
$('#saveFlash').onclick=()=>{$$('.flash-score').forEach(x=>run.teams[+x.dataset.i].flash=Math.max(0,Math.min(10,+x.value||0)));saveRun();renderScoreboard();toast('Skor Flash Pitch tersimpan.')};
function renderEvaluation(){const valid=students.filter(s=>s.name.trim());const pre=valid.map(s=>+s.pre).filter(Number.isFinite),post=valid.map(s=>+s.post).filter(Number.isFinite);const avg=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0;const ap=avg(pre),ao=avg(post),inc=ao-ap;$('#evalMetrics').innerHTML=`<div class="metric"><span class="label">Jumlah Siswa</span><strong>${valid.length}</strong></div><div class="metric"><span class="label">Rata-rata Pre-Test</span><strong>${ap.toFixed(1)}</strong></div><div class="metric"><span class="label">Rata-rata Post-Test</span><strong>${ao.toFixed(1)}</strong></div><div class="metric"><span class="label">Peningkatan</span><strong>${inc>=0?'+':''}${inc.toFixed(1)}</strong></div>`;$('#evalChart').innerHTML=valid.length?valid.map(s=>{const a=Math.max(0,Math.min(100,+s.pre||0)),b=Math.max(0,Math.min(100,+s.post||0));return `<div style="padding:14px 0;border-bottom:1px solid var(--line)"><b>${esc(s.name)}</b><div class="chart"><span class="muted mini">Pre-Test</span><div class="bar-shell"><div class="bar" style="width:${a}%"></div></div><b>${a}</b></div><div class="chart"><span class="muted mini">Post-Test</span><div class="bar-shell"><div class="bar" style="width:${b}%"></div></div><b>${b}</b></div></div>`}).join(''):'<div class="notice">Belum ada data siswa. Isi Pre-Test dan Post-Test terlebih dahulu.</div>'}
renderSetup();renderBoard();
